Feature/create contributing doc
ODNZSL/nzsl-online pull request #405
Opened 2018-10-07 22:37 UTC by louise-r-blue

This is the first PR for the contributing markdown file which includes the code of conduct. Would be good to get this up as the project is now open source. Please check esp the areas (typos and language) before and after the code of conduct.

2018-10-07 22:46 UTC, ghostPepperWonton approved these changes
Super minor thing you can choose to address: Some of the paragraphs are capped columns (looks like 80 columns), but some are as long as the line you have. There are some plugins to autoformat that and make it consistent. Looks good though!

2018-10-07 22:56 UTC, louise-r-blue commented
@danieljauch what do you think is the best/optimal paragraph width?

2018-10-08 02:04 UTC, Br3nda commented on .editorconfig
> +preferred_line_length = 80
i've been using 120 -- 80 is a bit of an old standard, and it's rare to find a screen that small now.
:elephant:

2018-10-08 02:05 UTC, Br3nda requested changes
editor config as 120 would be better -- or at least match it to the rubocop linter config

2018-10-08 02:05 UTC, Br3nda commented on .editorconfig
> +preferred_line_length = 80
We should match our rubocop settings too -- so actually 120 is a better idea i think

2018-10-08 02:06 UTC, Br3nda commented
the contributor docs looks fabulous. maybe the editor config change should be on a different PR ?

2018-10-08 02:26 UTC, louise-r-blue commented on .editorconfig
> +preferred_line_length = 80
Ok I have removed line 14 from the config.

2018-10-08 02:27 UTC, louise-r-blue commented
@Br3nda all done I think

2018-10-08 03:30 UTC, Br3nda approved these changes

2018-10-08 20:26 UTC, merged